[package]
name = "manue-desk"
version = "0.1.0"
edition = "2021"
description = "A modern .desktop file creator for Linux distros"
authors = ["Syed Sameer Ul Hassan"]
license = "Apache-2.0"

[dependencies]
slint = "1.8"
rfd = "0.15"

[build-dependencies]
slint-build = "1.8"

[package.metadata.deb]
maintainer = "Syed Sameer Ul Hassan <manuedesk@orildo.sbs>"
copyright = "2026, Syed Sameer Ul Hassan <manuedesk@orildo.sbs>"
license-file = ["LICENSE", "4"]
extended-description = "A modern, fluid .desktop file creator application for Linux desktop environments."
section = "utility"
priority = "optional"
assets = [
    ["target/release/manue-desk", "usr/bin/manue-desk", "755"],
    ["ui/assets/app-icon.svg", "usr/share/icons/hicolor/scalable/apps/manue-desk.svg", "644"],
    ["manue-desk.desktop", "usr/share/applications/manue-desk.desktop", "644"],
]

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/manue-desk", dest = "/usr/bin/manue-desk", mode = "755" },
    { source = "ui/assets/app-icon.svg", dest = "/usr/share/icons/hicolor/scalable/apps/manue-desk.svg", mode = "644" },
    { source = "manue-desk.desktop", dest = "/usr/share/applications/manue-desk.desktop", mode = "644" },
]
